### PR TITLE
AMQNET-585: NMS AMQP .NetStd 2.0 Client Support

### PR DESCRIPTION
**Pull request by HavretGC**
- Add .NET Standard support
- Add nuget package configuration
- Update dependencies
- Add Microsoft.NET.Test.Sdk to be able to run tests directly form VS
- Get the directory containing the current test assembly properly
- Fix race condition on .NET Core

In previous implementation, CountDownLatch was instantiated after
OpenResponse subscription was made. It might lead to race conditions
when the connection was established before proper instance CountDownLatch
was set. As a result attempt to call Connect would end up with timeout.
For whatever reasons it wasn't a case with .NET Framework set as
a target framework, but happens every single time when you try to run
tests against .NET Core runtime.

### CODE REVIEW

**Comment by mpoutlook** [comment]
LGTM.

**Comment by michaelandrepearce** [comment]
LGTM

**Comment by RagnarPaulson** [comment]
I've discussed this with @cjwmorgan-sol who is the expert on the inner working of this project here. We believe this pull request removes support for .NET Framework prior to 4.6 and focuses on .NET core. 

This is fine, as .NET core is the goal and runs everywhere. Just so long as that is the intent.

Otherwise looks good to us.  Good catch on the CountDownLatch issue.  It's great to see this moving forward.  If there are any deeper technical questions I'll step aside and let Chris Morgan respond.

**Comment by cjwmorgan-sol** [comment]
This is great! I did notice the NMS API dependency references a new version, 1.8.0, of Apache.NMS one could not find in nuget.org. I saw a pull request for netstandard2.0 support for the Apache NMS project, see https://github.com/apache/activemq-nms-api/pull/4. 

It might be difficult to build this project without that pull request and a new NMS api release and publish to nuget.org. Unless there is some other public package source that not aware of that has the new version.

It might be a good idea to wait to merge this until the 1.8.0 Apache.NMS api is released. :)

**Comment by HavretGC** [comment]
@RagnarPaulson  To be precise everything below **net461** is out of the picture, as you can see [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

**Comment by michaelpearce-gain** [comment]
@RagnarPaulson it was intent is as this didnt get released still, to avoid bringing too much old bagage and simplfy to support .netstd and above. 

@cjwmorgan-sol the intent is this is dependant on the nms-api change, thats in PR, i am leaving it some time just to give people a chance to review before i merge it, please if you could check the nms-api pr, and if you dont see any issues +1 it, more reviewers the better imo. re this PR, as code never got released, we're not in a situation to need to do emergency bug release, is it a real blocker to merge it before the other?

**Comment by HavretGC** [comment]
@RagnarPaulson @cjwmorgan-sol Would it be ok with you if I rearrange the solution a little in this PR? What I have in mind is to clean up all *.cproj files from redundant entries and move all of the source code to more .nettish location. For now *.cproj files are in one directory and actual source code in the other. It makes working with solution really painful.  All source files need to be explicitly included, you cannot add new files using IDE, etc...

My plan is to arrange it in sth like this:
image

**Comment by RagnarPaulson** [comment]
Makes sense to me.  It would bring make the project layout more consistent with other NMS transports like activemq-nms-openwire.

**Comment by michaelandrepearce** [comment]
Hi @RagnarPaulson @cjwmorgan-sol @artnaseef and anyone else.

Myself and @HavretGC would like to briefly discuss face to face some changes we are working on, and get any feedback, which may require a little refactor.

If you can make it, it would be great, will be hosting the meeting via Zoom (30 minutes):

* Introductions (5mins)
* Krzysztof + Mike to go over our goal (5mins)
* Krzysztof to discuss current challenges and the refactors he'd like to do (10mins)
* Others intent, and feedback, AOB (10mins)

=====================================================

Michael Pearce is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://zoom.us/j/499366173

One tap mobile
+442030512874,,499366173# United Kingdom 442036950088,,499366173# United 
+Kingdom

Dial by your location
        +44 203 051 2874 United Kingdom
        +44 203 695 0088 United Kingdom
        +44 203 966 3809 United Kingdom
        +1 646 558 8656 US (New York)
        +1 408 638 0968 US (San Jose)
        +1 647 558 0588 Canada
Meeting ID: 499 366 173
Find your local number: https://zoom.us/u/abKkYVjYzP

**Comment by michaelpearce-gain** [comment]
Thanks for joining us guys, great to hear your interest and involvement in NMS AMQP.
As noted if you want to see the work in progress before further PR's we're looking to work here:
https://github.com/cityindex/activemq-nms-amqp

**Comment by michaelpearce-gain** [comment]
failover work, is currently in this branch https://github.com/cityindex/activemq-nms-amqp/tree/failover_implementation in case you are interested..

**Comment by RagnarPaulson** [comment]
Thanks Michael.   Looks like a good start.  Chris is going through it and we’ll post some feedback shortly.

Ragnar

**Comment by HavretGC** [comment]
Hi @RagnarPaulson, I created a WIP PR to make going trough it easier for you guys. https://github.com/apache/activemq-nms-amqp/pull/4

**Comment by michaelpearce-gain** [comment]
As https://github.com/apache/activemq-nms-api/pull/4 is now merged will merge this.

**Pull request merged**
