### PR TITLE
AMQNET-746 NmsContext event listeners

### PR DESCRIPTION
**Pull request by lukeabsent**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@Havret / @lukeabsent  whats occuring with this, is a discussion needed? or is it dead / no longer relavent?

**Comment by Havret** [comment]
Sorry, I'd need a bit more context to understand this change. @lukeabsent

**Comment by lukeabsent** [comment]
@Havret / @michaelandrepearce  I think this should still be needed change (of coures pls validate), 
if you take a look into NMSContext, there are some events, but are not implemented (they dont fire), is that right ?

**Review by Havret — APPROVED** [review]
LGTM

**Pull request merged**
