### PR TITLE
AMQNET-624: Fix failover issue when broker sends open frame and shortly after close frame

### PR DESCRIPTION
**Pull request by HavretGC**
This PR addresses https://issues.apache.org/jira/browse/AMQNET-624.

### CODE REVIEW

**Comment by Havret** [comment]
@cjwmorgan-sol Could you please take a look at this?

**Comment by cjwmorgan-sol** [comment]
Looks good and tests pass. 

The only thing is running TriggerReconnectionAttempt outside of lock(SyncRoot) by using Task.Run(). Does this occur? (I'm not too strong in using async task pattern with locking) The FailoverProvider underlying provider seems to be manipulated safely only under the lock(SyncRoot) however I believe there is no lock(SyncRoot) in InitializeNewConnection allowing old providers to be left opened and live. I was able to add a log in InitializeNewConnection to check if an old provider was still there from the FailoverProvider.provider field and I was able to see logs FailoverProvider.provider having an old value during InitializeNewConnection. 

@Havret Should that be possible?

**Comment by Havret** [comment]
@cjwmorgan-sol No it shouldn't. I've tried to reproduce what you did but with no lack. Nevertheless I've revoked the Task.Run change, as it shouldn't be part of this PR. 

With all that being said, I think we should revisit this part of code  (mainly TriggerReconnectionAttempt) after we hopefully deliver initial release.

**Comment by cjwmorgan-sol** [comment]
Sounds good to me.

The PR looks good.

**Pull request merged**
