### PR TITLE
Merge 2.0.x into master

### PR DESCRIPTION
**Pull request by michaelandrepearce**
For maintenance current master i have branched to 1.8.x.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@lukeabsent / @Havret  / @cjwmorgan-sol  - Merge is so we can now release 2.0.x

**Review by Havret — APPROVED** [review]

**Comment by clebertsuconic** [comment]
I really dislike Merge Commits.. do you really need then?


I have always preferred git cherry-pick -x...


I have then used a project to associated cherry-picks and find the ones that are missing.

**Comment by clebertsuconic** [comment]
with the gitreport I wrote, I can find references on cherry-pick -x... and you would be able to find the ones missing.

**Comment by michaelandrepearce** [comment]
@clebertsuconic this is a whole lot of work that has been collaborative committed to. Theres no point cherry picking some 20ish commits.

**Comment by Havret** [comment]
@michaelandrepearce @clebertsuconic Merge with rebase is superior to both of your approaches. :)

**Pull request merged**
