### PR TITLE
NO-JIRA: Enable interop tests for Travis

### PR DESCRIPTION
**Pull request by Havret**
It seems that we can run interop tests on travis using Artemis running via docker. One of the tests is failing because of the bug in Artemis (I am using 2.9.0 version), but otherwise it looks fine.

### CODE REVIEW

**Comment by Havret** [comment]
It seems that we can run interop tests on travis. One of the tests is failing because I am using Artemis 2.9.0 docker image, but otherwise it work fine.

**Comment by Havret** [comment]
I ignored failing test. It should be restored after https://github.com/vromero/activemq-artemis-docker/pull/124 is merged and we can use Artemis 2.10.0

**Comment by michaelandrepearce** [comment]
@havret we should use the apache artemis docker build. Not an external one

**Comment by michaelandrepearce** [comment]
https://github.com/apache/activemq-artemis/tree/master/artemis-docker

**Comment by Havret** [comment]
It it available on docker hub?

**Comment by michaelandrepearce** [comment]
No but you can build on fly or work with artemis for next release to get it so

**Comment by Havret** [comment]
I looked how it's done in official Artemis repo and I don't see it coming any time soon, as it would require decoupling docker bits from the rest of the repo as we don't want to publish docker images on every build, but on every release. Exactly how it's done by @vromero. 

Couldn't we just use as it is, as @vromero images are using official apache artifacts anyway?

**Comment by michaelandrepearce** [comment]
@Havret based on there isnt still an apache docker, there is one at artemiscloud, and vromero has archived to keep prs to active ones im closing this out, if you disagree and have updates to this please re-p[em

**Comment by Havret** [comment]
@michaelandrepearce I wasn't able to run artemiscloud, but for https://github.com/Havret/dotnet-activemq-artemis-client tests I switched to a custom image https://hub.docker.com/r/havret/dotnet-activemq-artemis-client-test-broker which contains just bare Artemis without any extra configuration. Maybe we can use it here?

**Pull request closed without merging**
