### PR TITLE
AMQNET-591: Transactions support

### PR DESCRIPTION
**Pull request by HavretGC**
This PR introduces transactions support. 

@cjwmorgan-sol @RagnarPaulson could you please take a look at it?

### CODE REVIEW

**Comment by cjwmorgan-sol** [comment]
I've been taking a look at the source code changes there look alright to me.
I've starting testing against two brokers, one that supports transactions (activemq artemis 2.9.0) and one that does not (solace broker).
It has taken me some sometime to verify the changes as I've some run into issues that I think are unrelated to the transport support, at least on the solace broker, that could be fixed.  (not sure if this is the right place to discuss those though)
I tried out the transaction sample which worked however the tests did not. I'm not sure why the interop tests do not work. None of the test seem to receive the message from the transaction.

@HavretGC Have you tried the tests against a broker, or is that why you raise #9 ?

**Comment by michaelandrepearce** [comment]
@cjwmorgan-sol @ragnarpaulson wanting to merge this in the next day or so, as its been open for a bit, would be great to get feedback though even if a simple +1.

Also after this i will think about spinning a release, unless we think any other major bits needed.

**Comment by cjwmorgan-sol** [comment]
@michaelandrepearce Currently The provider does not work for the solace broker for two main reasons:
1) MessageProducer rate are 1 msg/sec on brokers that respect the batchable flag for amqp transfers. This has been a long standing issue with amqpnetlite until it was fixed for synchronous sends, version 2.1.8. The provider AmqpProducer uses async sends with ManualResetEvent to block. This is bad in term of amqp protocol as the transfer sent as batchable indicating to the broker that disposition should not be sent right away so it waits however the client is also waiting for a response leading to terrible message rates. Amqpnetlite fixed this issue at least for synchronous sends from a sender link where the batchable flag is set to false when a send is synchronous however that means that AmqpProducer must use a different send (see senderLink.send(msg) and senderLink.send(msg, timeout)) method then its currently using.
2) local expiration of messages by the provider is on, localMessageExpiry sends modified outcomes for expired ttl, which some brokers do not support. The qpid doc indicate this property is on by defualt however looking through the code it does not appear to be. This problem is far more apparent in combination with 1) as ttl expiration is far more like to occur for slower messages rates, and reasonable ttl defaults. Adding a localMessageExpiry property would greatly help.

For a release I'd say 1) should be be resolved as the provider is not acting correct for the amqp protocol its producing. For 2) as far as I can tell should not that big of a change and have the provider support brokers that do not support local message expiry a little better. Also would make the provider be a little more like qpid jms anyways.

As for transactions I could get only the sample transaction project to hang at rollback. And the new interop tests did not worked at all. I also got some weird packet captures during the tests and the sample which make it a little difficult for a +1 at least for transactions. It might be worth looking into first. However, if your confident that the transaction work for your brokers of choice.

I checked that the provider fails gracefully with the solace broker for transaction so it "works" for broker that do not support amqp transactions. So for transaction I can give a +1 for that.

**Comment by michaelandrepearce** [comment]
@cjwmorgan-sol to discuss the transactions so we can maybe see first hand whats failing for you. Maybe we could organise some sort of screen share? Im keen not to ignore issues, as could be serious. Would you mind if we scheduled?

**Comment by michaelandrepearce** [comment]
On point 2, whats the behaviour in qpid jms? Im keen we keep aligned

**Comment by Havret** [comment]
@cjwmorgan-sol Do all interop tests hang on rollback? I was running them regularly during development phase and everything was passing except one test which was failing because of a bug in Apache Artemis (which was reported to RedHat).

**Comment by cjwmorgan-sol** [comment]
@HavretGC I found some transactions that involved sending/receiving messages failed due to a 60s timeout (possibly a transaction commit or rollback?) other are other failures with different causes. Ie consumer closed after rollback, consumer.receive(timeout) return null, etc. This is using activemq artemis 2.9.0. I have yet to dig into the individual causes for the failures in detail.  I also noticed the from a packet capture the router and the client seem to sending and receive "malformed amqp" packets. Not sure how much amqp transaction support wireshark dissectors have though.

@michaelandrepearce for the localMessageExpiry property qpid jms can be configured at connection to have consumer delivery ttl expired messages. In qpid jms see JmsMessageConsumer.java field consumerExpiredMessage and consumerInfo.isLocalMessageExpiry() and connectionInfo.isLocalMessageExpiry(). According to the document, see [JMS Configuration options](https://qpid.apache.org/releases/qpid-jms-0.44.0/docs/index.html#jms-configuration-options), this property is set to true by default. However the code does not seem to have the property to true by default. (It is set to an uninitialized boolean which would be false, however I might be missing something there I would need to confirm).  Maybe there is a bug in the docs there?

**Comment by cjwmorgan-sol** [comment]
@HavretGC I think I found the source of my issue. When the TTL is set to default on the producer the amqp field expiry time is set on out going message to "1/1/0001 5:00:00 AM" where the DateTime.minValue is "1/1/0001 12:00:00 AM". This caused all my consumed messages to be expired and dropped locally. Looks like the AbsoluteExpiry time get set send the session on send. I'm not if this should be done as the [jms mapping document](https://www.oasis-open.org/committees/download.php/59981/amqp-bindmap-jms-v1.0-wd07.pdf) states that if the ttl is 0 the AbsoluteExpiry must be omitted rather then set to zero, see sections 3.3.2 and 3.2.1. If I comment out the section of code :
```
if (hasTTL)
                outbound.Facade.Expiration = timeStamp + timeToLive;
 //else
                //outbound.Facade.Expiration = DateTime.MinValue;
```
from NmsSession.Send my interop tests start passing (with only two failures) and the transaction sample works.

I notice qpid jms has a special set the absoluteExpiryTime to null when given a value of 0 or null to the facade. I'm not sure if this is possible with the interface provided by amqpnetlite as DateTime is a struct and must have value. It might be possible to work around this by creating a Properties instance (which has null for absoluteExpiryTime) and copy all other values without setting the absoluteExpiryTime for when setting the Expiration to 0. Not to keen on that though the interface for the amqpnetlite message should be enhanced to be able to set a null absoluteExpiryTime.

Reguardless currently the provider in not creating amqp frames with the correct absoluteExpiryTime field.
@HavretGC and @michaelandrepearce what do you think?

**Comment by Havret** [comment]
My inclination would be to send PR to amqpnetlite which would change AbsoluteExpiryTime type to nullable DateTime.

**Comment by Havret** [comment]
My inclination would be to send PR to amqpnetlite which would change AbsoluteExpiryTime type to nullable DateTime and update our logic accordingly. But I am afraid that this would be a breaking change for amqpnetlite. :(

@xinchen10 What do you think? Is it doable?

**Comment by michaelandrepearce** [comment]
Can we check with openwire if we are exposing the nmsx extension parameters for transaction the same

**Comment by HavretGC** [comment]
@michaelandrepearce  TBH I'm not sure if it can be done that way, as TransactionId is part of the Transfer frame, and not the payload itself, thus we don't have access to it. It's part of amqpnetlite internals. I don't see this exposed in qpid jms either.

**Comment by HavretGC** [comment]
Replaced by https://github.com/apache/activemq-nms-amqp/pull/14

**Pull request closed without merging**
