### PR TITLE
AMQNET-735 Add AsyncMessageListener to Consumer API

### PR DESCRIPTION
**Pull request by Havret**
It depends on https://github.com/apache/activemq-nms-api/pull/26

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
I thought API was merged?

**Comment by Havret** [comment]
The API got merged but hasn't been released yet. I was holding out for a solid nms-amqp implementation. Now that I've got one, I've kicked off the release process for nms-api version 2.1.0.

**Comment by Havret** [comment]
nms.api is merged and released. @michaelandrepearce @lukeabsent could you please take a look?

**Comment by michaelandrepearce** [comment]
+1 form me. @lukeabsent ?

**Comment by michaelandrepearce** [comment]
@lukeabsent please review also else will look to merge soon (end of week)

**Comment by bertvan** [comment]
Hi @Havret is it possible this change did not make it into the Apache.NMS.AMQP 2.2 package?
https://www.nuget.org/packages/Apache.NMS.AMQP

We're using Apache.NMS.AMQP 2.2 and Apache.NMS 2.1 packages, but receive a System.TypeLoadException:
Method 'add_AsyncListener' in type 'Apache.NMS.AMQP.NmsMessageConsumer' ... does not have an implementation.

It seems there are no corresponding (github) tags associated to check this.
The version at https://activemq.apache.org/components/nms/providers/amqp/downloads/ doesn't contain it.
The version at https://www.nuget.org/packages/Apache.NMS.AMQP/2.2.0 doesn't contain it.

```
Method 'add_AsyncListener' in type 'Apache.NMS.AMQP.NmsMessageConsumer' from assembly 'Apache.NMS.AMQP, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation. 

System.TypeLoadException    
at Apache.NMS.AMQP.NmsSession..ctor(NmsConnection connection, NmsSessionId sessionId, AcknowledgementMode acknowledgementMode)    
at Apache.NMS.AMQP.NmsConnection.CreateSessionAsync(AcknowledgementMode acknowledgementMode)    
at Apache.NMS.AMQP.Util.Synchronization.TaskExtensions.GetAsyncResult[T](Task`1 task)    
at Apache.NMS.AMQP.NmsConnection.CreateSession(AcknowledgementMode acknowledgementMode) 
```

**Comment by dazzabaijan** [comment]
Hi, getting the exact same problem here, with the exact same packages versions and the exact same exceptions. Has this been looked at?
Thanks.

**Pull request merged**
