### PR TITLE
AMQNET-610: Race conditions during consumer creation

### PR DESCRIPTION
**Pull request by Havret**
It closes https://issues.apache.org/jira/projects/AMQNET/issues/AMQNET-610

@michaelandrepearce @cjwmorgan-sol Could you please take a look?

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
LGTM, will give it another 24hrs before merging so @cjwmorgan-sol  gets a chance to look

**Comment by cjwmorgan-sol** [comment]
Seem pretty good to me however I did find one exception when trying to shutdown a connection with live traffic:
PubSubLogger 9/10/2019 12:44:06 PM Error: Exception occurred: Apache.NMS.IllegalStateException: The Session is closed
   at Apache.NMS.AMQP.NmsSession.CheckClosed()
   at Apache.NMS.AMQP.NmsSession.get_AcknowledgementMode()
   at Apache.NMS.AMQP.NmsMessageConsumer.SetAcknowledgeCallback(InboundMessageDispatch envelope)
   at Apache.NMS.AMQP.NmsMessageConsumer.OnInboundMessage(InboundMessageDispatch envelope)
   at Apache.NMS.AMQP.NmsSession.OnInboundMessage(InboundMessageDispatch envelope)
   at Apache.NMS.AMQP.NmsConnection.OnInboundMessage(InboundMessageDispatch envelope)
   at Apache.NMS.AMQP.Provider.Failover.FailoverProvider.OnInboundMessage(InboundMessageDispatch envelope)
   at Apache.NMS.AMQP.Provider.Amqp.AmqpConsumer.OnMessage(IReceiverLink receiver, Message amqpMessage)
   at Amqp.ReceiverLink.OnTransfer(Delivery delivery, Transfer transfer, ByteBuffer buffer)
   at Amqp.Session.OnTransfer(Transfer transfer, ByteBuffer buffer)
   at Amqp.Connection.OnFrame(ByteBuffer buffer)



I believe this can be fixed by using the Session.SessionInfo.AcknowledgementMode instead of Session.AcknowledgementMode in the Apache.NMS.AMQP.NmsMessageConsumer.SetAcknowledgeCallback method. I tried this and it worked. However, this seems somewhat odd to though as my application called stop on the connection before closing the connection.

**Comment by Havret** [comment]
Hi Chris,

I see where it may come from:

https://github.com/apache/activemq-nms-amqp/blob/3c7ecd5c1b11d7211027293e4e4b38f05c21e0d9/src/NMS.AMQP/NmsMessageConsumer.cs#L399-L409

In line 405 we are using AcknowledgementMode property of session, and there is a check there which throws exception when connection is closed. 

In qpid jms they have this helper method ```isIndividualAcknowledge``` which circumvents the check that sits inside the getter. I remember asking myself during the implementation, why the heck they have this method when they can make the check directly. Apparently I've got my answer. 

```
if (acknowledgementMode == Session.CLIENT_ACKNOWLEDGE) {
    envelope.getMessage().setAcknowledgeCallback(new JmsAcknowledgeCallback(session));
} else if (session.isIndividualAcknowledge()) {
    envelope.getMessage().setAcknowledgeCallback(new JmsAcknowledgeCallback(session, envelope));
}
```

https://github.com/apache/qpid-jms/blob/94822aced1380bae7935db6305250bf6bea7a9ac/qpid-jms-client/src/main/java/org/apache/qpid/jms/JmsMessageConsumer.java#L497-L501

@cjwmorgan-sol Could you be kindly enough to file an issue, so it could be fixed in a separate PR?

**Comment by cjwmorgan-sol** [comment]
Raised https://issues.apache.org/jira/browse/AMQNET-611, this PR looks fine to me.

**Comment by HavretGC** [comment]
@michaelandrepearce It is ready to merge then.

**Comment by michaelandrepearce** [comment]
@HavretGC did we resolve the issue robbie raised in dev mail list re object msg

**Comment by Havret** [comment]
I'm going to look at it tonight.

**Comment by Havret** [comment]
Yep. But it would be nice to have [this one](https://issues.apache.org/jira/projects/AMQNET/issues/AMQNET-611) included in the initial release as well. It will be a quick fix though.

**Comment by michaelandrepearce** [comment]
Ok. Just remember there will always be bugs. We do want to cut a release at somepoint. Once we have a release done we can always do another in a few more weeks.

**Pull request merged**
